version: "3.8"

services:
  appdelante:
    build:
      context: .
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - SERVER_PORT=3000
    volumes:
      - ./:/app:ro
      - /app/node_modules
    command: npm run debug